
CREATE TABLE CLIENTES
(
COD_CLI NUMBER PRIMARY KEY,
NOME_CLI VARCHAR(50),
RG_CLI VARCHAR(9),
CPF_CLI VARCHAR(11) UNIQUE,
SITUACAO VARCHAR(20)
);
CREATE TABLE EDITORAS
(
COD_EDI NUMBER PRIMARY KEY,
NOME_EDI VARCHAR(50),
ENDERECO VARCHAR(100),
TELEFONE VARCHAR(20)
);
CREATE TABLE LIVROS
(
CODIGO_LIV NUMBER PRIMARY KEY,
TITULO_LIV VARCHAR(100),
AUTOR VARCHAR(50),
ANO NUMBER,
VALOR_LIV NUMBER(7,2),
QUANTIDADE_EST NUMBER,
EDITORA NUMBER,
CONSTRAINT FK_EDITORA FOREIGN KEY (EDITORA) REFERENCES EDITORAS (COD_EDI)
);
CREATE TABLE PEDIDOS
(
ID NUMBER PRIMARY KEY,
DATA_PEDIDO DATE,
VALOR_PEDIDO NUMBER(10,2),
SITUACAO VARCHAR(20),
COD_CLI NUMBER,
CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLI) REFERENCES CLIENTES(COD_CLI)
);
CREATE TABLE ITENSPED
(
LIVRO NUMBER,
PEDIDO NUMBER,
QUANTIDADE NUMBER,
CONSTRAINT FK_LIVRO_PEDIDO FOREIGN KEY (LIVRO) REFERENCES LIVROS(CODIGO_LIV),
CONSTRAINT FK_PEDIDO FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID)
);
CREATE TABLE LIVROSFALTA
(
ID NUMBER PRIMARY KEY,
NOME VARCHAR(100),
AUTOR VARCHAR(50),
ANO NUMBER,
STATUS VARCHAR(20),
PEDIDO NUMBER,
CONSTRAINT FK_PEDIDO_FALTA FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID)
);
CREATE TABLE PEDIDOAQ
(
ID NUMBER PRIMARY KEY,
DATA_PEDIDO DATE,
VALOR_PEDIDO NUMBER(10,2),
SITUACAO VARCHAR(20),
COD_EDI NUMBER,
CONSTRAINT FK_EDITORA_AQ FOREIGN KEY (COD_EDI) REFERENCES EDITORAS(COD_EDI)
);
CREATE TABLE ITENSAQ
(
LIVRO_FALTA NUMBER,
PEDIDO_AQ NUMBER,
QUANTIDADE NUMBER,
CONSTRAINT FK_LIVRO_FALTA FOREIGN KEY (LIVRO_FALTA) REFERENCES LIVROSFALTA(ID),
CONSTRAINT FK_PEDIDO_AQ FOREIGN KEY (PEDIDO_AQ) REFERENCES PEDIDOAQ(ID)
);
INSERT INTO CLIENTES VALUES (1, 'ERICK', '262727282', '83838383900', 'ATIVO');
INSERT INTO CLIENTES VALUES (2, 'JOÃO', '262727282', '83838383901', 'INATIVO');
INSERT INTO CLIENTES VALUES (3, 'PAULA', '262727282', '83838383902', 'ATIVO');
INSERT INTO EDITORAS VALUES (1, 'BRASPORT', 'Rua A, 123', '123456789');
INSERT INTO EDITORAS VALUES (2, 'EDITORA B', 'Rua B, 456', '987654321');
INSERT INTO LIVROS VALUES (1, 'LIVRO A', 'MARIANA', 2022, 40, 10, 1);

INSERT INTO LIVROS VALUES (2, 'LIVRO B', 'EDSON', 2021, 150, 5, 1);
INSERT INTO LIVROS VALUES (3, 'LIVRO C', 'CARLA', 2020, 300, 7, 2);

SELECT * 
FROM CLIENTES
WHERE NOME_CLI LIKE '%A%';

SELECT TITULO_LIV
FROM LIVROS
WHERE AUTOR = 'EDSON';

SELECT AUTOR
FROM LIVROS
WHERE TITULO_LIV = 'LIVRO A';

SELECT NOME_EDI
FROM EDITORAS
ORDER BY NOME_EDI DESC;
